version: "3.7"

services:

  azure_storage:
    image: "mcr.microsoft.com/azure-storage/azurite:3.18.0"
    container_name: "azurite"
    restart: "always"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
